/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.field.Display',
        'Ext.chart.Chart',
        'Ext.util.Point',
        'Ext.chart.series.Pie',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Column',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.button.Button'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 150,
                    title: 'Menu',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'home',
                                    text: 'Home'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'store',
                                    text: 'Store'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'sale',
                                    text: 'Sale'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'rating',
                                    text: 'Rating'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'chart',
                                    text: 'Chart'
                                }
                            ],
                            listeners: {
                                click: {
                                    fn: me.onMenuClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    activeItem: 3,
                    itemId: 'contentPanel',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'chartPanel',
                            title: 'Chart',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            fieldLabel: '',
                                                            value: 'Grafik Stok Musik'
                                                        },
                                                        {
                                                            xtype: 'chart',
                                                            height: 250,
                                                            width: 400,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'musicChartStore',
                                                            series: [
                                                                {
                                                                    type: 'pie',
                                                                    label: {
                                                                        field: 'label',
                                                                        display: 'rotate',
                                                                        contrast: true,
                                                                        font: '12px Arial'
                                                                    },
                                                                    showInLegend: true,
                                                                    angleField: 'jumlah'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            fieldLabel: '',
                                                            value: 'Grafik Penjualan Musik'
                                                        },
                                                        {
                                                            xtype: 'chart',
                                                            height: 250,
                                                            width: 400,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'musicChartSale',
                                                            axes: [
                                                                {
                                                                    type: 'Category',
                                                                    fields: [
                                                                        'label'
                                                                    ],
                                                                    position: 'left',
                                                                    title: 'Genre'
                                                                },
                                                                {
                                                                    type: 'Numeric',
                                                                    fields: [
                                                                        'jumlah'
                                                                    ],
                                                                    position: 'bottom',
                                                                    title: 'Jumlah'
                                                                }
                                                            ],
                                                            series: [
                                                                {
                                                                    type: 'bar',
                                                                    label: {
                                                                        display: 'insideEnd',
                                                                        field: 'jumlah',
                                                                        color: '#333',
                                                                        'text-anchor': 'middle'
                                                                    },
                                                                    axis: 'bottom',
                                                                    xField: 'label',
                                                                    yField: 'jumlah'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            width: '',
                                                            fieldLabel: 'Grafik Pembelian Musik Berdasarkan Umur',
                                                            labelWidth: 400
                                                        },
                                                        {
                                                            xtype: 'chart',
                                                            height: 250,
                                                            width: 400,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'musicChartAge',
                                                            axes: [
                                                                {
                                                                    type: 'Category',
                                                                    fields: [
                                                                        'umur'
                                                                    ],
                                                                    title: 'Umur Pembeli',
                                                                    position: 'bottom'
                                                                },
                                                                {
                                                                    type: 'Numeric',
                                                                    fields: [
                                                                        'jumlah'
                                                                    ],
                                                                    title: 'Jumlah',
                                                                    position: 'left'
                                                                }
                                                            ],
                                                            series: [
                                                                {
                                                                    type: 'column',
                                                                    label: {
                                                                        display: 'insideEnd',
                                                                        field: 'label',
                                                                        color: '#333',
                                                                        'text-anchor': 'middle'
                                                                    },
                                                                    xField: 'umur',
                                                                    yField: 'jumlah'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'salePanel',
                            title: 'Sale',
                            items: [
                                {
                                    xtype: 'container',
                                    margin: 10,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'edtSaleFilter',
                                            width: '',
                                            fieldLabel: 'Judul Musik'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'tableSale',
                                    title: 'Data Penjualan',
                                    store: 'saleStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            align: 'center',
                                            dataIndex: 'no',
                                            text: 'No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            align: 'center',
                                            dataIndex: 'music_title',
                                            text: 'Judul Musik'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            align: 'center',
                                            dataIndex: 'costumer_name',
                                            text: 'Nama Pembeli'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'costumer_age',
                                            text: 'Umur Pembeli'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            align: 'center',
                                            dataIndex: 'music_genre',
                                            text: 'Genre'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'total_purchase',
                                            text: 'Jumlah Beli'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'total_price',
                                            text: 'Total'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'storePanel',
                            title: 'Store',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    dock: 'top',
                                    cls: 'action-container',
                                    padding: '',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            itemId: 'btnBuyMusic',
                                            margin: 10,
                                            maxWidth: 200,
                                            padding: 5,
                                            width: 150,
                                            text: 'Beli'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            itemId: 'btnAddRating',
                                            margin: 10,
                                            maxWidth: 200,
                                            padding: 5,
                                            width: 150,
                                            text: 'Tambah Rating'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    dock: 'top',
                                    margin: 10,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'edtStoreFilter',
                                            width: 400,
                                            fieldLabel: 'Nama Musik atau Penyanyi',
                                            labelWidth: 200
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    dock: 'top',
                                    itemId: 'tableStore',
                                    title: 'Data Musik',
                                    store: 'musicStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            align: 'center',
                                            dataIndex: 'no',
                                            text: 'No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '35%',
                                            align: 'center',
                                            dataIndex: 'music_title',
                                            text: 'Judul Musik'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            align: 'center',
                                            dataIndex: 'music_singer',
                                            text: 'Penyanyi'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'music_genre',
                                            text: 'Genre'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'music_stock',
                                            text: 'Stock'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'music_price',
                                            text: 'Harga'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'homePanel',
                            title: 'Home',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    cls: 'action-container',
                                    height: 50,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            margins: '0 10 0 0',
                                            itemId: 'btnAddMusic',
                                            maxWidth: 150,
                                            padding: '5 10',
                                            width: 150,
                                            text: 'Tambah Musik'
                                        },
                                        {
                                            xtype: 'button',
                                            margins: '0 10',
                                            disabled: true,
                                            itemId: 'btnEditMusic',
                                            minWidth: 150,
                                            padding: '5 10',
                                            text: 'Edit Musik'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            itemId: 'btnDeleteMusic',
                                            minWidth: 150,
                                            padding: '5 10',
                                            text: 'Hapus Musik'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    dock: 'top',
                                    margin: 10,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'edtMusicFilter',
                                            width: 400,
                                            fieldLabel: 'Nama Musik atau Penyanyi',
                                            labelWidth: 200,
                                            name: ''
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    dock: 'top',
                                    itemId: 'tableMusic',
                                    title: 'Data Music',
                                    titleAlign: 'left',
                                    store: 'musicStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            align: 'center',
                                            dataIndex: 'no',
                                            text: 'No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '35%',
                                            align: 'center',
                                            dataIndex: 'music_title',
                                            text: 'Judul Musik'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            align: 'center',
                                            dataIndex: 'music_singer',
                                            text: 'Penyanyi'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'music_genre',
                                            text: 'Genre'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'music_stock',
                                            text: 'Stock'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'music_price',
                                            text: 'Harga'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'ratingPanel',
                            title: 'Rating',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            itemId: 'btnEditRating',
                                            margin: 10,
                                            padding: 5,
                                            width: 150,
                                            text: 'Ubah Rating'
                                        },
                                        {
                                            xtype: 'button',
                                            disabled: true,
                                            itemId: 'btnDeleteRating',
                                            margin: 10,
                                            padding: 5,
                                            width: 150,
                                            text: 'Hapus Rating'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'tableRating',
                                    store: 'ratingStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            align: 'center',
                                            dataIndex: 'no',
                                            text: 'No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            align: 'center',
                                            dataIndex: 'music_title',
                                            text: 'Judul Musik'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            align: 'center',
                                            dataIndex: 'costumer_name',
                                            text: 'Nama Pelanggan'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '15%',
                                            align: 'center',
                                            dataIndex: 'music_genre',
                                            text: 'Genre'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '15%',
                                            align: 'center',
                                            dataIndex: 'costumer_rating',
                                            text: 'Rating'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    }

});