/*
 * File: app/view/window_purchase.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.window_purchase', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_purchase',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Display',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 300,
    width: 400,
    title: 'Beli Musik',
    titleAlign: 'center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: '',
                            name: 'id_music'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            itemId: 'music_price',
                            fieldLabel: 'Harga',
                            name: 'music_price'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'costumer_name',
                            fieldLabel: 'Nama Pembeli',
                            name: 'costumer_name',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'costumer_age',
                            fieldLabel: 'Umur Pembeli',
                            name: 'costumer_age',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'amountPurchase',
                            fieldLabel: 'Jumlah Beli',
                            name: 'total_purchase',
                            allowBlank: false,
                            blankText: 'Harus diisi',
                            minValue: 1
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            itemId: 'totalPrice',
                            fieldLabel: 'Total Harga',
                            name: 'totalPrice',
                            value: 0
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            itemId: 'totalPriceShow',
                            fieldLabel: 'Total Harga',
                            name: 'totalPrice',
                            value: '0'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'totalPurchase',
                            fieldLabel: 'Total Bayar',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '',
                            cls: 'warning-text',
                            hidden: true,
                            itemId: 'negative_balance',
                            fieldLabel: '',
                            labelAlign: 'right',
                            value: 'Uang kurang'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnPurchase',
                            margin: 30,
                            width: 70,
                            text: 'Bayar'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCancelPurchase',
                            width: 70,
                            text: 'Batal'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});