/*
 * File: app/view/window_music.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.window_music', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_music',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 300,
    width: 400,
    title: 'Dialog Musik',
    titleAlign: 'center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'id_music'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: '',
                            fieldLabel: 'Judul',
                            name: 'music_title',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: '',
                            fieldLabel: 'Penyanyi',
                            name: 'music_singer',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Genre',
                            name: 'music_genre',
                            allowBlank: false,
                            blankText: 'Harus diisi',
                            displayField: 'music_genre',
                            queryMode: 'local',
                            store: 'genreStore',
                            valueField: 'kode'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Stock',
                            name: 'music_stock'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Harga',
                            name: 'music_price',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'button',
                            cls: 'form-button',
                            itemId: 'btnSave',
                            margin: 30,
                            width: 70,
                            text: 'Simpan'
                        },
                        {
                            xtype: 'button',
                            cls: 'form-button',
                            componentCls: 'form-button',
                            itemId: 'btnCancel',
                            margin: '',
                            width: 70,
                            text: 'Batal'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});