/*
 * File: app/view/window_rating.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.window_rating', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_rating',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 320,
    width: 400,
    title: 'Dialog Rating',
    titleAlign: 'center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            name: 'id_music'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Nama',
                            name: 'costumer_name',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Umur',
                            name: 'costumer_age',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Rating',
                            name: 'costumer_rating',
                            allowBlank: false,
                            blankText: 'Harus diisi',
                            maxValue: 5,
                            minValue: 1
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 100,
                            fieldLabel: 'Komentar',
                            name: 'costumer_comment',
                            allowBlank: false,
                            blankText: 'Harus diisi'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSaveRating',
                            margin: 30,
                            width: 70,
                            text: 'Simpan'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCancelRating',
                            margin: '',
                            width: 70,
                            text: 'Batal'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});