/*
 * File: app/model/saleModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.model.saleModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'no'
        },
        {
            name: 'costumer_name'
        },
        {
            name: 'costumer_age'
        },
        {
            name: 'music_title'
        },
        {
            name: 'music_genre'
        },
        {
            name: 'total_purchase'
        },
        {
            name: 'total_price'
        }
    ]
});