/*
 * File: app/controller/chartController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.controller.chartController', {
    extend: 'Ext.app.Controller',

    onPanelBoxReady: function(component, width, height, eOpts) {
        Ext.getStore('musicChartStore').load();
        Ext.getStore('musicChartSale').load();
        Ext.getStore('musicChartAge').load();
    },

    onChartShow: function(component, eOpts) {
        Ext.getStore('musicChartStore').load();
        Ext.getStore('musicChartSale').load();
        Ext.getStore('musicChartAge').load();
    },

    init: function(application) {
        this.control({
            "#chartPanel": {
                boxready: this.onPanelBoxReady,
                show: this.onChartShow
            }
        });
    }

});
