/*
 * File: app/controller/ratingController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.controller.ratingController', {
    extend: 'Ext.app.Controller',

    onPanelShow: function(component, eOpts) {
        Ext.getStore('ratingStore').load();
    },

    onPanelBoxReady: function(component, width, height, eOpts) {
        Ext.getStore('ratingStore').load();
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        Ext.ComponentQuery.query('#btnEditRating')[0].setDisabled(false);
        Ext.ComponentQuery.query('#btnDeleteRating')[0].setDisabled(false);
    },

    onDeleteRatingClick: function(button, e, eOpts) {
        var hapus = function(btn){
            if(btn == "yes"){
                var grid = Ext.ComponentQuery.query('#tableRating')[0];
                var selection = grid.getSelectionModel().getSelection()[0];

                var idRating  = selection.get('id_rating');

                if(selection){
                    Ext.Ajax.request({
                        url : 'api/music/rating/deleteRating.php',
                        params :{
                            id_rating : idRating
                        },
                        success:function(response, opts){
                            var response = Ext.decode(response.responseText);
                            if(response.success){
                                Ext.getStore('ratingStore').load();
                            }else{
                                Ext.MessageBox.show({
                                    title : "Peringatan",
                                    msg: response.message,
                                    buttons: Ext.MessageBox.OK,
                                    icon : Ext.MessageBox.INFO
                                });
                            }
                        }
                    });
                }
            }
        };

        Ext.MessageBox.show({
            title: "Peringatan",
            msg: "Apakah anda yakin ingin menghapus rating ini ?",
            buttons: Ext.MessageBox.YESNO,
            icon: Ext.MessageBox.QUESTION,
            fn: hapus
        });
    },

    init: function(application) {
        this.control({
            "#ratingPanel": {
                show: this.onPanelShow,
                boxready: this.onPanelBoxReady
            },
            "#tableRating": {
                selectionchange: this.onGridpanelSelectionChange
            },
            "#btnDeleteRating": {
                click: this.onDeleteRatingClick
            }
        });
    }

});
